import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import { Layout } from '@/components/layout/Layout';
import Head from 'next/head';
import { SessionProvider } from 'next-auth/react';
import { NextUIProvider } from '@nextui-org/react';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import { lightTheme } from '../themes/lightTheme';
import { darkTheme } from '../themes/darktheme';

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <>
      <Head>
        <title>Chefier</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SessionProvider session={session}>
        <NextThemesProvider
          defaultTheme='system'
          attribute='class'
          value={{
            light: lightTheme.className,
            dark: darkTheme.className,
          }}
        >
          <NextUIProvider>
            <main>
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </main>
          </NextUIProvider>
        </NextThemesProvider>
      </SessionProvider>
    </>
  );
}
