import '@/styles/globals.css';
import type { AppProps } from 'next/app';
<<<<<<< HEAD

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
=======
import { Layout } from '@/components/layout/Layout';
import Head from 'next/head';
import { Raleway } from '@next/font/google';
import { SessionProvider } from 'next-auth/react';

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <>
      <Head>
        <title>Chefier</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SessionProvider session={session}>
        <main className={`${raleway.variable} ${raleway.className}`}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </main>
      </SessionProvider>
    </>
  );
>>>>>>> develop
}
