name: Coveralls

on:
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  Coveralls:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installing dependencies frontend
      run: npm i

    - name: Installing dependencies backend
      working-directory: ./server
      run: npm i
    
    - name: Generating coverage information
      run: npm run coverage
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Coveralls Scan
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}