name: SonarCloud

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

jobs:
  SonarCloud:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installing dependencies frontend
      run: npm i

    - name: Installing dependencies backend
      working-directory: ./server
      run: npm i
    
    - name: Generating coverage information
      run: npm run coverage
      env:
        DATABASE_URL: ${{ secrets.SONARCLOUD_DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        IMAGEKIT_ENDPOINT: ${{ secrets.IMAGEKIT_ENDPOINT }}
   
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}