name: Tests

on:
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "develop", "main" ]

jobs:

  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Testing backend
      working-directory: ./server
      run: npm i && npm run coverage
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Testing frontend
      run: npm i && npm run coverage